def lerne_python():
    print("\n")
    print("Lerne Python")
    print("\n")
    print("[1] Lektion 1: print() ")
    print("[2] Lektion 2: Dateien importieren mit import <Datei> ")
    print("[3] Lektion 3: Variablen ")
    print("[4] Lektion 4: Eine eigene Funktion definieren ")
    print("\n")
    eingabe = input("> ")
    if int(eingabe) == 1:
        print("\n")
        print("Lektion 1: print() ")
        print("\n")
        print("Texte kannst du mit")
        print("print() ausgeben!")
        print("\n")
        print("Zum Beispiel so")
        print('print("Hallo Welt!")'')
        print(", nun wird der Text")
        print("Hallo Welt! ausgegeben")
        print("\n")
    elif int(eingabe) == 2:
        print("\n")
        print("Lektion 2: Dateien importieren mit import <Datei> ")
        print("\n")
        print("Mit import <Datei> kannst du")
        print("eine Datei mit Pythoncode")
        print("importieren. Das sieht dann")
        print("genau so aus:")
        print("\n")
        print("programm.py Inhalt:")
        print("\n")
        print('print("Hallo Welt")')
        print("\n")
        print("\n")
        print("programm2.py Inhalt:")
        print("\n")
        print("import programm")
        print("\n")
    elif int(eingabe) == 3:
        print("\n")
        print("Lektion 3: Variablen")
        print("\n")
        print("Variablen mit einem Integer-Wert")
        print("werden so gesetzt:")
        print("\n")
        print("<Variablenname> = <Integer>")
        print("\n")
        print("Ein Integer-Wert ist eine natürliche")
        print("Zahl die keine Dezimalzahl sein darf.")
        print("\n")
        print("Beispiel:")
        print("\n")
        print("meinevariable = 1")
        print("\n")
        print("Variablen können in den Print-Befehl eingebaut")
        print("werden, dass dann so aussieht:")
        print("\n")
        print('print(meinevariable)')
        print("\n")
        print("oder")
        print("\n")
        print('print(1)')
        print("\n")
    elif int(eingabe) == 4:
        print("\n")
        print("Lektion 4: Eine eigene Funktion definieren")
        print("\n")
        print("Mit dem def-Befehl kannst du deine eigene")
        print("Funktion definieren. Beispiel:")
        print("\n")
        print("def MeineFunktion():")
        print('      print("Hallo Welt!")')
        print("\n")
        print("Deine eigenen Funktion kannst du auch mit")
        print("einem anderen Python-Programme öffnen:")
        print("\n")
        print("programm.py Inhalt:")
        print("\n")
        print("def MeineFunktion():")
        print('      print("Hallo Welt!")')
        print("\n")
        print("\n")
        print("programm2.py Inhalt:")
        print("\n")
        print("import programm")
        print("programm.MeineFunktion()")
        print("\n")
