def news():
  print("\n")
  print("News")
  print("\n")
  print("UPDATE: Es wird bald eine 1.3 geben!")
  print("\n")
  print("Was wird neu sein?")
  print("\n")
  print("- Neue Apps für die App ExtraApps")
  print("- Whatsapp via Selenium wird verfügbar sein")
  print("- SecureBrowser (Apache) wird verfügbar sein")
  print("- JannOSAntivirus wird verfügbar sein")
  print("- RawWeb (Apache) wird verfügbar sein")
  print("\n")
  print("Stand: 08.03.2020")
  print("Zum aktualisieren bitte neuinstallieren oder ab der 1.3")
  print("in der ExtraApp news aktualisieren auswählen")
  time.sleep(2)
